// @generated by scripts/generate-scope.mjs — do not edit manually

import React, {useState, useCallback, useMemo, useEffect, useRef} from 'react';

const stylexMock = {
  create: <T extends Record<string, unknown>>(styles: T): T => styles,
  props: (..._styles: unknown[]) => ({className: '', style: {} as Record<string, string>}),
  defineVars: <T extends Record<string, unknown>>(tokens: T): T => tokens,
  keyframes: (kf: Record<string, Record<string, string>>) => kf,
  types: {angle: (v: string) => v, color: (v: string) => v, image: (v: string) => v, integer: (v: string) => v, length: (v: string) => v, lengthPercentage: (v: string) => v, number: (v: string) => v, percentage: (v: string) => v, resolution: (v: string) => v, time: (v: string) => v, transformFunction: (v: string) => v, transformList: (v: string) => v, url: (v: string) => v},
};

import * as AlertDialog from '@xds/core/AlertDialog';
import * as AppShell from '@xds/core/AppShell';
import * as AspectRatio from '@xds/core/AspectRatio';
import * as Avatar from '@xds/core/Avatar';
import * as Badge from '@xds/core/Badge';
import * as Banner from '@xds/core/Banner';
import * as Breadcrumbs from '@xds/core/Breadcrumbs';
import * as Button from '@xds/core/Button';
import * as Calendar from '@xds/core/Calendar';
import * as Card from '@xds/core/Card';
import * as Carousel from '@xds/core/Carousel';
import * as Center from '@xds/core/Center';
import * as Chat from '@xds/core/Chat';
import * as CheckboxInput from '@xds/core/CheckboxInput';
import * as CheckboxList from '@xds/core/CheckboxList';
import * as ClickableCard from '@xds/core/ClickableCard';
import * as CodeBlock from '@xds/core/CodeBlock';
import * as Collapsible from '@xds/core/Collapsible';
import * as CommandPalette from '@xds/core/CommandPalette';
import * as DateInput from '@xds/core/DateInput';
import * as Dialog from '@xds/core/Dialog';
import * as Divider from '@xds/core/Divider';
import * as DropdownMenu from '@xds/core/DropdownMenu';
import * as EmptyState from '@xds/core/EmptyState';
import * as Field from '@xds/core/Field';
import * as FormLayout from '@xds/core/FormLayout';
import * as Grid from '@xds/core/Grid';
import * as HoverCard from '@xds/core/HoverCard';
import * as Icon from '@xds/core/Icon';
import * as IconButton from '@xds/core/IconButton';
import * as Kbd from '@xds/core/Kbd';
import * as Layer from '@xds/core/Layer';
import * as Layout from '@xds/core/Layout';
import * as Link from '@xds/core/Link';
import * as List from '@xds/core/List';
import * as Markdown from '@xds/core/Markdown';
import * as MetadataList from '@xds/core/MetadataList';
import * as MobileNav from '@xds/core/MobileNav';
import * as MoreMenu from '@xds/core/MoreMenu';
import * as MultiSelector from '@xds/core/MultiSelector';
import * as NavIcon from '@xds/core/NavIcon';
import * as NavMenu from '@xds/core/NavMenu';
import * as NumberInput from '@xds/core/NumberInput';
import * as OverflowList from '@xds/core/OverflowList';
import * as Overlay from '@xds/core/Overlay';
import * as Pagination from '@xds/core/Pagination';
import * as Popover from '@xds/core/Popover';
import * as PowerSearch from '@xds/core/PowerSearch';
import * as ProgressBar from '@xds/core/ProgressBar';
import * as RadioList from '@xds/core/RadioList';
import * as Resizable from '@xds/core/Resizable';
import * as Section from '@xds/core/Section';
import * as SegmentedControl from '@xds/core/SegmentedControl';
import * as SelectableCard from '@xds/core/SelectableCard';
import * as Selector from '@xds/core/Selector';
import * as SideNav from '@xds/core/SideNav';
import * as SizeContext from '@xds/core/SizeContext';
import * as Skeleton from '@xds/core/Skeleton';
import * as Slider from '@xds/core/Slider';
import * as Spinner from '@xds/core/Spinner';
import * as Stack from '@xds/core/Stack';
import * as StatusDot from '@xds/core/StatusDot';
import * as Switch from '@xds/core/Switch';
import * as TabList from '@xds/core/TabList';
import * as Table from '@xds/core/Table';
import * as Text from '@xds/core/Text';
import * as TextArea from '@xds/core/TextArea';
import * as TextInput from '@xds/core/TextInput';
import * as Thumbnail from '@xds/core/Thumbnail';
import * as TimeInput from '@xds/core/TimeInput';
import * as Timestamp from '@xds/core/Timestamp';
import * as Toast from '@xds/core/Toast';
import * as ToggleButton from '@xds/core/ToggleButton';
import * as Token from '@xds/core/Token';
import * as Tokenizer from '@xds/core/Tokenizer';
import * as Toolbar from '@xds/core/Toolbar';
import * as Tooltip from '@xds/core/Tooltip';
import * as TopNav from '@xds/core/TopNav';
import * as TreeList from '@xds/core/TreeList';
import * as Typeahead from '@xds/core/Typeahead';

import {defaultTheme} from '@xds/theme-default/built';
import {neutralTheme} from '@xds/theme-neutral/built';
import {dailyTheme} from '@xds/theme-daily/built';
import {matchaTheme} from '@xds/theme-matcha/built';

import {XDSTheme} from '@xds/core/theme';
import type {XDSDefinedTheme} from '@xds/core/theme';
import {createElement, type ComponentProps} from 'react';
import * as xdsTokens from '@xds/core/theme/tokens.stylex';

import * as Heroicons16Solid from '@heroicons/react/16/solid';
import * as Heroicons20Solid from '@heroicons/react/20/solid';
import * as Heroicons24Outline from '@heroicons/react/24/outline';
import * as Heroicons24Solid from '@heroicons/react/24/solid';

const SCOPE_THEMES: Record<string, XDSDefinedTheme> = {
  default: defaultTheme,
  neutral: neutralTheme,
  daily: dailyTheme,
  matcha: matchaTheme,
};

const ControlledXDSTheme = (props: ComponentProps<typeof XDSTheme>) => {
  const win = typeof window !== 'undefined'
    ? (window as unknown as Record<string, unknown>)
    : null;
  const mode = (win?.__xds_preview_mode__ as 'light' | 'dark' | 'system') || 'system';
  const themeName = (win?.__xds_preview_theme__ as string) || 'default';
  const theme = SCOPE_THEMES[themeName] ?? defaultTheme;
  return createElement(XDSTheme, {...props, theme, mode});
};

export const scope: Record<string, Record<string, unknown>> = {
  'react': {default: React, ...React, useState, useCallback, useMemo, useEffect, useRef},
  '@stylexjs/stylex': {default: stylexMock, ...stylexMock},
  'stylex': {default: stylexMock, ...stylexMock},
  '@xds/theme-default': {default: defaultTheme, defaultTheme},
  '@xds/theme-default/built': {default: defaultTheme, defaultTheme},
  '@xds/theme-neutral': {default: neutralTheme, neutralTheme},
  '@xds/theme-neutral/built': {default: neutralTheme, neutralTheme},
  '@xds/theme-daily': {default: dailyTheme, dailyTheme},
  '@xds/theme-daily/built': {default: dailyTheme, dailyTheme},
  '@xds/theme-matcha': {default: matchaTheme, matchaTheme},
  '@xds/theme-matcha/built': {default: matchaTheme, matchaTheme},
  '@xds/core/theme': {XDSTheme: ControlledXDSTheme},
  '@xds/core/theme/tokens.stylex': xdsTokens,
  '@xds/core/AlertDialog': AlertDialog,
  '@xds/core/AppShell': AppShell,
  '@xds/core/AspectRatio': AspectRatio,
  '@xds/core/Avatar': Avatar,
  '@xds/core/Badge': Badge,
  '@xds/core/Banner': Banner,
  '@xds/core/Breadcrumbs': Breadcrumbs,
  '@xds/core/Button': Button,
  '@xds/core/Calendar': Calendar,
  '@xds/core/Card': Card,
  '@xds/core/Carousel': Carousel,
  '@xds/core/Center': Center,
  '@xds/core/Chat': Chat,
  '@xds/core/CheckboxInput': CheckboxInput,
  '@xds/core/CheckboxList': CheckboxList,
  '@xds/core/ClickableCard': ClickableCard,
  '@xds/core/CodeBlock': CodeBlock,
  '@xds/core/Collapsible': Collapsible,
  '@xds/core/CommandPalette': CommandPalette,
  '@xds/core/DateInput': DateInput,
  '@xds/core/Dialog': Dialog,
  '@xds/core/Divider': Divider,
  '@xds/core/DropdownMenu': DropdownMenu,
  '@xds/core/EmptyState': EmptyState,
  '@xds/core/Field': Field,
  '@xds/core/FormLayout': FormLayout,
  '@xds/core/Grid': Grid,
  '@xds/core/HoverCard': HoverCard,
  '@xds/core/Icon': Icon,
  '@xds/core/IconButton': IconButton,
  '@xds/core/Kbd': Kbd,
  '@xds/core/Layer': Layer,
  '@xds/core/Layout': Layout,
  '@xds/core/Link': Link,
  '@xds/core/List': List,
  '@xds/core/Markdown': Markdown,
  '@xds/core/MetadataList': MetadataList,
  '@xds/core/MobileNav': MobileNav,
  '@xds/core/MoreMenu': MoreMenu,
  '@xds/core/MultiSelector': MultiSelector,
  '@xds/core/NavIcon': NavIcon,
  '@xds/core/NavMenu': NavMenu,
  '@xds/core/NumberInput': NumberInput,
  '@xds/core/OverflowList': OverflowList,
  '@xds/core/Overlay': Overlay,
  '@xds/core/Pagination': Pagination,
  '@xds/core/Popover': Popover,
  '@xds/core/PowerSearch': PowerSearch,
  '@xds/core/ProgressBar': ProgressBar,
  '@xds/core/RadioList': RadioList,
  '@xds/core/Resizable': Resizable,
  '@xds/core/Section': Section,
  '@xds/core/SegmentedControl': SegmentedControl,
  '@xds/core/SelectableCard': SelectableCard,
  '@xds/core/Selector': Selector,
  '@xds/core/SideNav': SideNav,
  '@xds/core/SizeContext': SizeContext,
  '@xds/core/Skeleton': Skeleton,
  '@xds/core/Slider': Slider,
  '@xds/core/Spinner': Spinner,
  '@xds/core/Stack': Stack,
  '@xds/core/StatusDot': StatusDot,
  '@xds/core/Switch': Switch,
  '@xds/core/TabList': TabList,
  '@xds/core/Table': Table,
  '@xds/core/Text': Text,
  '@xds/core/TextArea': TextArea,
  '@xds/core/TextInput': TextInput,
  '@xds/core/Thumbnail': Thumbnail,
  '@xds/core/TimeInput': TimeInput,
  '@xds/core/Timestamp': Timestamp,
  '@xds/core/Toast': Toast,
  '@xds/core/ToggleButton': ToggleButton,
  '@xds/core/Token': Token,
  '@xds/core/Tokenizer': Tokenizer,
  '@xds/core/Toolbar': Toolbar,
  '@xds/core/Tooltip': Tooltip,
  '@xds/core/TopNav': TopNav,
  '@xds/core/TreeList': TreeList,
  '@xds/core/Typeahead': Typeahead,
  '@xds/core': {...AlertDialog, ...AppShell, ...AspectRatio, ...Avatar, ...Badge, ...Banner, ...Breadcrumbs, ...Button, ...Calendar, ...Card, ...Carousel, ...Center, ...Chat, ...CheckboxInput, ...CheckboxList, ...ClickableCard, ...CodeBlock, ...Collapsible, ...CommandPalette, ...DateInput, ...Dialog, ...Divider, ...DropdownMenu, ...EmptyState, ...Field, ...FormLayout, ...Grid, ...HoverCard, ...Icon, ...IconButton, ...Kbd, ...Layer, ...Layout, ...Link, ...List, ...Markdown, ...MetadataList, ...MobileNav, ...MoreMenu, ...MultiSelector, ...NavIcon, ...NavMenu, ...NumberInput, ...OverflowList, ...Overlay, ...Pagination, ...Popover, ...PowerSearch, ...ProgressBar, ...RadioList, ...Resizable, ...Section, ...SegmentedControl, ...SelectableCard, ...Selector, ...SideNav, ...SizeContext, ...Skeleton, ...Slider, ...Spinner, ...Stack, ...StatusDot, ...Switch, ...TabList, ...Table, ...Text, ...TextArea, ...TextInput, ...Thumbnail, ...TimeInput, ...Timestamp, ...Toast, ...ToggleButton, ...Token, ...Tokenizer, ...Toolbar, ...Tooltip, ...TopNav, ...TreeList, ...Typeahead},
  '@heroicons/react/16/solid': Heroicons16Solid,
  '@heroicons/react/20/solid': Heroicons20Solid,
  '@heroicons/react/24/outline': Heroicons24Outline,
  '@heroicons/react/24/solid': Heroicons24Solid,
  'next/image': {default: (props: Record<string, unknown>) => React.createElement('img', props)},
};
