#!/usr/bin/env node

/**
 * Generates apps/docsite/src/app/playground/preview/scope.ts
 *
 * Maps every XDS module available in the playground preview iframe.
 * Run: node scripts/generate-scope.mjs
 */

import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const CORE_PKG = resolve(ROOT, '../../packages/core/package.json');
const OUT = resolve(ROOT, 'src/app/playground/preview/scope.ts');

const HEADER = '// @generated by scripts/generate-scope.mjs \u2014 do not edit manually';

// Read core package.json exports and extract PascalCase component subpaths
const corePkg = JSON.parse(readFileSync(CORE_PKG, 'utf-8'));
const exportKeys = Object.keys(corePkg.exports ?? {});

const SKIP = /\.(css|stylex)$|\/utils$|^\.\/theme|^\.\/hooks|^\.\/utils|^\.\/syntax|^\.\/docs|^\.\/groups|^\.$|^\.\/reset/;

const components = exportKeys
  .filter((k) => {
    if (SKIP.test(k)) return false;
    const name = k.replace('./', '');
    return /^[A-Z]/.test(name);
  })
  .map((k) => k.replace('./', ''));

// Themes
const SCOPE_THEMES = [
  {pkg: '@xds/theme-default', name: 'defaultTheme', subpath: '/built'},
  {pkg: '@xds/theme-neutral', name: 'neutralTheme', subpath: '/built'},
  {pkg: '@xds/theme-daily', name: 'dailyTheme', subpath: '/built'},
  {pkg: '@xds/theme-matcha', name: 'matchaTheme', subpath: '/built'},
];

// Heroicons variants
const HEROICON_VARIANTS = [
  {path: '16/solid', alias: 'Heroicons16Solid'},
  {path: '20/solid', alias: 'Heroicons20Solid'},
  {path: '24/outline', alias: 'Heroicons24Outline'},
  {path: '24/solid', alias: 'Heroicons24Solid'},
];

// Build output
const lines = [HEADER, ''];

// React
lines.push("import React, {useState, useCallback, useMemo, useEffect, useRef} from 'react';");
lines.push('');

// StyleX mock
lines.push('const stylexMock = {');
lines.push("  create: <T extends Record<string, unknown>>(styles: T): T => styles,");
lines.push("  props: (..._styles: unknown[]) => ({className: '', style: {} as Record<string, string>}),");
lines.push("  defineVars: <T extends Record<string, unknown>>(tokens: T): T => tokens,");
lines.push("  keyframes: (kf: Record<string, Record<string, string>>) => kf,");
lines.push("  types: {angle: (v: string) => v, color: (v: string) => v, image: (v: string) => v, integer: (v: string) => v, length: (v: string) => v, lengthPercentage: (v: string) => v, number: (v: string) => v, percentage: (v: string) => v, resolution: (v: string) => v, time: (v: string) => v, transformFunction: (v: string) => v, transformList: (v: string) => v, url: (v: string) => v},");
lines.push('};');
lines.push('');

// Component imports
for (const name of components) {
  lines.push(`import * as ${name} from '@xds/core/${name}';`);
}
lines.push('');

// Theme imports
for (const t of SCOPE_THEMES) {
  lines.push(`import {${t.name}} from '${t.pkg}${t.subpath}';`);
}
lines.push('');

// XDSTheme + tokens
lines.push("import {XDSTheme} from '@xds/core/theme';");
lines.push("import * as xdsTokens from '@xds/core/theme/tokens.stylex';");
lines.push('');

// Heroicons
for (const h of HEROICON_VARIANTS) {
  lines.push(`import * as ${h.alias} from '@heroicons/react/${h.path}';`);
}
lines.push('');

// ControlledXDSTheme wrapper
lines.push(`const ControlledXDSTheme = (props: Record<string, unknown>) => {`);
lines.push(`  const mode = (typeof window !== 'undefined' && (window as any).__xds_preview_mode__) || 'system';`);
lines.push(`  const themeName = (typeof window !== 'undefined' && (window as any).__xds_preview_theme__) || 'default';`);
lines.push(`  const THEMES: Record<string, unknown> = {`);
for (const t of SCOPE_THEMES) {
  lines.push(`    '${t.name.replace('Theme', '').toLowerCase()}': ${t.name},`);
}
lines.push(`  };`);
lines.push(`  const theme = (THEMES[themeName] ?? ${SCOPE_THEMES[0].name}) as any;`);
lines.push(`  return React.createElement(XDSTheme, {...props, theme, mode});`);
lines.push(`};`);
lines.push('');

// Scope map
lines.push('export const scope: Record<string, Record<string, unknown>> = {');

// react
lines.push("  'react': {default: React, ...React, useState, useCallback, useMemo, useEffect, useRef},");

// stylex
lines.push("  '@stylexjs/stylex': {default: stylexMock, ...stylexMock},");
lines.push("  'stylex': {default: stylexMock, ...stylexMock},");

// themes
for (const t of SCOPE_THEMES) {
  lines.push(`  '${t.pkg}': {default: ${t.name}, ${t.name}},`);
  lines.push(`  '${t.pkg}/built': {default: ${t.name}, ${t.name}},`);
}

// XDSTheme (controlled wrapper)
lines.push("  '@xds/core/theme': {XDSTheme: ControlledXDSTheme},");

// tokens.stylex
lines.push("  '@xds/core/theme/tokens.stylex': xdsTokens,");

// Per-component subpath entries
for (const name of components) {
  lines.push(`  '@xds/core/${name}': ${name},`);
}

// Barrel export — all components spread
lines.push(`  '@xds/core': {${components.map((n) => `...${n}`).join(', ')}},`);

// Heroicons
for (const h of HEROICON_VARIANTS) {
  lines.push(`  '@heroicons/react/${h.path}': ${h.alias},`);
}

// next/image stub
lines.push("  'next/image': {default: (props: Record<string, unknown>) => React.createElement('img', props)},");

lines.push('};');
lines.push('');

// Write output
mkdirSync(dirname(OUT), {recursive: true});
writeFileSync(OUT, lines.join('\n'));
console.log(`✓ Generated ${OUT}`);
console.log(`  ${components.length} components`);
console.log(`  ${SCOPE_THEMES.length} themes`);
console.log(`  ${HEROICON_VARIANTS.length} heroicon variants`);
