/**
 * @file tsup.config.ts
 * @input Uses tsup
 * @output Bundle configuration for CJS/ESM outputs (DTS via separate tsc pass)
 * @position Build config; defines entry points and output formats for @xds/core
 *
 * DTS is generated by a separate `tsc --project tsconfig.build.json` step
 * instead of tsup's built-in `dts: true`. This avoids OOM — tsup instantiates
 * a full TypeScript program per entry point (60+), while tsc does one pass.
 *
 * SYNC: When modified, update this header and /packages/core/README.md
 */

import {defineConfig} from 'tsup';
import babel from 'esbuild-plugin-babel';

export default defineConfig({
  entry: ['src/index.ts', 'src/*/index.ts', 'src/theme/tokens.stylex.ts', 'src/theme/syntax/index.ts'],
  format: ['cjs', 'esm'],
  dts: false,
  splitting: true,
  metafile: true,
  clean: true,
  external: ['react', 'react-dom'],
  noExternal: ['@stylexjs/stylex', 'styleq'],
  esbuildPlugins: [
    babel({
      filter: /\.[jt]sx?$/,
      config: {
        presets: [
          ['@babel/preset-react', {runtime: 'automatic'}],
          '@babel/preset-typescript',
        ],
        plugins: [
          [
            '@stylexjs/babel-plugin',
            {
              dev: false,
              runtimeInjection: false,
              genConditionalClasses: true,
              treeshakeCompensation: true,
              unstable_moduleResolution: {
                type: 'commonJS',
                rootDir: '.',
              },
            },
          ],
        ],
      },
    }),
  ],
});
